name: 'GHActions-SMS-Freemobile'
description: 'Github actions that notify on freemobile SMS.'
inputs:
  freemobile_user:
    description: 'The freemobile SMS API username.'
    required: true
  freemobile_password:
    description: 'The freemobile SMS API password.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'