name: 'GHActions-SMS-Freemobile'
description: 'Github actions that notify on freemobile SMS.'
inputs:
  event_name:
    description: 'The name of the event that triggered the workflow run.'
    required: true
  webhook_event:
    description: 'The full event webhook payload.'
    required: true
  freemobile_user:
    description: 'The freemobile SMS API username.'
    required: true
  freemobile_password:
    description: 'The freemobile SMS API password.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'