name: 'GHActions-SMS-Freemobile'
description: 'Github actions that notify on freemobile SMS.'
inputs:
  event_name:
    description: 'The name of the event that triggered the workflow run.'
    required: true
  repository:
    description: 'The Repository Name.'
    required: true
  sender:
    description: 'The Sender Name.'
    required: true
  pushRef:
    description: 'The ref of the push event'
    required: false
  action:
    description: 'The action of the event'
    required: false
  number:
    description: 'The number of the event'
    required: false
  title:
    description: 'The title of the event'
    required: false
  freemobile_user:
    description: 'The freemobile SMS API username.'
    required: true
  freemobile_password:
    description: 'The freemobile SMS API password.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'