name: 'GHActions-SMS-Freemobile'
description: 'Github actions that notify on freemobile SMS.'
inputs:
  repository:
    description: 'The Repository Name.'
    required: true
  sender:
    description: 'The Sender Name.'
    required: true
  pushRef:
    description: 'The ref of the push event'
    required: true
  freemobile_user:
    description: 'The freemobile SMS API username.'
    required: true
  freemobile_password:
    description: 'The freemobile SMS API password.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'